# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supervUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supervUi(object):
    def setupUi(self, supervUi):
        supervUi.setObjectName("supervUi")
        supervUi.resize(1440, 720)
        self.centralwidget = QtWidgets.QWidget(supervUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1440, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Ui/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1100, 550, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget) 
        self.pushButton_2.setGeometry(QtCore.QRect(1210, 550, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -40, 550, 220))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Ui/Jarvis_Loading_Screen.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1040, 30, 155, 40))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1200, 30, 161, 40))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px")
        self.textBrowser_2.setObjectName("textBrowser_2")
        supervUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(supervUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 18))
        self.menubar.setObjectName("menubar")
        supervUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(supervUi)
        self.statusbar.setObjectName("statusbar")
        supervUi.setStatusBar(self.statusbar)

        self.retranslateUi(supervUi)
        QtCore.QMetaObject.connectSlotsByName(supervUi)

    def retranslateUi(self, supervUi):
        _translate = QtCore.QCoreApplication.translate
        supervUi.setWindowTitle(_translate("supervUi", "MainWindow"))
        self.pushButton.setText(_translate("supervUi", "START"))
        self.pushButton_2.setText(_translate("supervUi", "END"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    supervUi = QtWidgets.QMainWindow()
    ui = Ui_supervUi()
    ui.setupUi(supervUi)
    supervUi.show()
    sys.exit(app.exec_())
